---
galaxy_info:
  author: Jose Riguera Lopez (jriguera@gmail.com)
  description: Install and setup Nginx (proxy or web) on RedHat/Debian based distributions
  license: Apache 2.0
  min_ansible_version: 2.0

  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - jessie

  categories:
    - web
    - proxy

dependencies: []

