---
ironic_inspector_release: "newton"
ironic_inspector_os_repo_url:
ironic_inspector_os_repo_key:

ironic_inspector_service_name: ironic-inspector
ironic_inspector_pidfile: /var/run/ironic-inspector/ironic-inspector.pid

ironic_inspector_user: ironic-inspector
ironic_inspector_group: ironic-inspector

ironic_inspector_config_file: /etc/ironic-inspector/inspector.conf
ironic_inspector_config_dir: /etc/ironic-inspector/
ironic_inspector_var_dir: /var/lib/ironic-inspector/

