---
dnsmasq_os_repo_url:
dnsmasq_os_repo_key:
dnsmasq_packages_install_recommends: True
# Upgrade the database if older than these seconds
# Time is only valid in Debian, set to 0/False to disable
dnsmasq_packages_update_cache: 1800

dnsmasq_daemon: dnsmasq
dnsmasq_user: dnsmasq
dnsmasq_group: nogroup

dnsmasq_pidfile: /var/run/dnsmasq.pid
dnsmasq_config_file: /etc/dnsmasq.conf
dnsmasq_config_dir: /etc/dnsmasq.d
dnsmasq_var_dir: /var/lib/dnsmasq
dnsmasq_config_addhosts: /etc/dnsmasq.hosts
dnsmasq_config_dhcphosts: /var/lib/dnsmasq/dhcp.leases
dnsmasq_config_dhcpscript: /var/lib/dnsmasq/script

