---
ironic_release: "newton"
ironic_os_repo_url:
ironic_os_repo_key:

ironic_conductor_service_name: ironic-conductor
ironic_conductor_pidfile: /var/run/ironic/ironic-conductor.pid

# Repository for auxiliary packages (shellinabox)
ironic_conductor_os_aux_repo_url:
ironic_conductor_os_aux_repo_key:
ironic_conductor_shellinabox_service_name: shellinabox

ironic_api_service_name: ironic-api
ironic_api_pidfile: /var/run/ironic/ironic-api.pid

ironic_user: ironic
ironic_group: ironic

ironic_config_file: /etc/ironic/ironic.conf
ironic_config_dir: /etc/ironic/
ironic_var_dir: /var/lib/ironic/

ironic_pxe_ipa_img_url: "http://tarballs.openstack.org/ironic-python-agent/coreos/files/coreos_production_pxe_image-oem-stable-{{ ironic_release }}.cpio.gz"
ironic_pxe_ipa_img_checksum: "sha1:1366b9f05d7827d07ac9c03bb1acfc7b7a8618c7"
ironic_pxe_ipa_img_name: "coreos_production_pxe_image-oem.cpio.gz"
ironic_pxe_ipa_kernel_url: "http://tarballs.openstack.org/ironic-python-agent/coreos/files/coreos_production_pxe-stable-{{ ironic_release }}.vmlinuz"
ironic_pxe_ipa_kernel_checksum: "sha1:934b1fd795557fd7b8b684507cfef008eeb664d9"
ironic_pxe_ipa_kernel_name: "coreos_production_pxe.vmlinuz"

ironic_pxe_tinyipa_img_url: "https://tarballs.openstack.org/ironic-python-agent/tinyipa/files/tinyipa-stable-{{ ironic_release }}.gz"
ironic_pxe_tinyipa_img_checksum: "sha1:005276172635b4f90751d2bcc86a9514bf252b00"
ironic_pxe_tinyipa_img_name: "tinyipa-master.gz"
ironic_pxe_tinyipa_kernel_url: "https://tarballs.openstack.org/ironic-python-agent/tinyipa/files/tinyipa-stable-{{ ironic_release }}.vmlinuz"
ironic_pxe_tinyipa_kernel_checksum: "sha1:1a936929b57a8d3f1ccc378d241103c5f1b93097"
ironic_pxe_tinyipa_kernel_name: "tinyipa-master.vmlinuz"

ironic_syslinux_basedir: /var/lib/ironic/pxeutils

ironic_pxe_syslinux_version: "6.03"
ironic_pxe_syslinux_tarball_checksum: "sha1:d215372c664109258dbc18b64e699afe1a4aaedd"
ironic_pxe_syslinux_tarball_url: "https://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.gz"

ironic_pxe_elilo_tarball_url: "http://heanet.dl.sourceforge.net/project/elilo/elilo/elilo-3.16/elilo-3.16-all.tar.gz"
ironic_pxe_elilo_tarball_checksum: "sha1:bd0bd4f1b3dc2d23a304f957ffbf907ae104f323"
ironic_pxe_shim_tarball_url: "http://archive.ubuntu.com/ubuntu/pool/main/s/shim-signed/shim-signed_1.12.tar.xz"
ironic_pxe_shim_tarball_checksum: "sha1:efe6213e393e9b715a92290b2b08cc1ad4221bf1"
ironic_pxe_grub2_url: "http://archive.ubuntu.com/ubuntu/dists/xenial/main/uefi/grub2-amd64/current/grubnetx64.efi.signed"
ironic_pxe_grub2_checksum: "sha1:f7dfa0cf34e98477aa9278ba82efa26dc8d2d2f3"

#ironic_pxe_ipxe_checksum:
ironic_pxe_ipxe_url: "http://boot.ipxe.org/undionly.kpxe"
#ironic_pxe_ipxe_uefi_checksum:
ironic_pxe_ipxe_uefi_url: "http://boot.ipxe.org/ipxe.efi"

