---
- name: Create configdrive temporary metadata folder
  file:
    path: "{{ configdrive_config_dir }}/{{ configdrive_instance_dir }}/{{ item }}"
    owner: "{{ configdrive_user | default(omit) }}"
    group: "{{ configdrive_group  | default(omit) }}"
    mode: 0755
    recurse: yes
    state: directory
  with_items:
    - "openstack/{{ configdrive_content_tmproot_dir }}"

- name: Setup temporary folder for include files
  set_fact: _configdrive_content_path="{{ configdrive_config_dir }}/{{ configdrive_instance_dir }}/openstack/{{ configdrive_content_tmproot_dir }}"

- include: ssh_public_key.yml
  when: not configdrive_ssh_public_key is defined or configdrive_ssh_public_key is none
  tags: ["configdrive", "ssh"]

- include: network.yml
  tags: ["configdrive", "network"]

- name: List the include files on temporary folder
  shell: find "{{ _configdrive_content_path }}" -type f | sed "s|{{ _configdrive_content_path }}||"
  register: __configdrive_content_files

- name: Get the include files on temporary folder
  set_fact: _configdrive_content_files="{{ __configdrive_content_files.stdout }}"

- name: Move files to destination from temporary folder
  command: mv "{{ _configdrive_content_path }}/{{ item.1 }}" "{{ configdrive_config_dir }}/{{ configdrive_instance_dir }}/openstack/content/{{ '%04d' % item.0|int }}"
  with_indexed_items: "{{ __configdrive_content_files.stdout_lines }}"

- name: Cleanup temporary folder
  file:
    state: absent
    force: yes
    name: "{{ _configdrive_content_path }}"

- name: Create meta_data.json
  template:
    src: meta_data.json.j2
    dest: "{{ configdrive_config_dir }}/{{ configdrive_instance_dir }}/{{ item }}/meta_data.json"
    owner: "{{ configdrive_user | default(omit) }}"
    group: "{{ configdrive_group | default(omit) }}"
    mode: 0644
  with_items:
    - "openstack/2012-08-10"
    - "openstack/latest"

- name: Copy user_data if defined
  copy:
    src: "{{ configdrive_config_user_data_path }}"
    dest: "{{ configdrive_config_dir }}/{{ configdrive_instance_dir }}/{{ item }}/user_data"
    owner: "{{ configdrive_user | default(omit) }}"
    group: "{{ configdrive_group | default(omit) }}"
    mode: 0644
  with_items:
    - "openstack/2012-08-10"
    - "openstack/latest"
  when: configdrive_config_user_data_path is defined

- name: Create config-2 volume
  shell: > 
    genisoimage -R -V "config-2" "{{ configdrive_config_dir }}/{{ configdrive_instance_dir }}" 
    | gzip -c | base64 > "{{ configdrive_volume_path }}/{{ configdrive_instance_dir }}.gz"
  when: configdrive_volume_path is defined and not configdrive_volume_path is none

