---
- name: Install required packages to create the images
  package:
    name: "{{ item.key }}"
    state: "{{ item.value.state | default('present') }}"
  with_dict: "{{ configdrive_required_packages }}"
  when: configdrive_check_required_packages
  tags: ["configdrive", "install", "packages"]

- name: Include OS specific variables
  include_vars: "{{ configdrive_os_family }}.yml"
  tags: ["distribution"]

- name: Setup configdrive instance folder
  set_fact: configdrive_instance_dir="{{ configdrive_uuid }}"
  when: configdrive_instance_dir is not defined or configdrive_instance_dir is none

- name: Create configdrive metadata folders
  file:
    path: "{{ configdrive_config_dir }}/{{ configdrive_instance_dir }}/{{ item }}"
    owner: "{{ configdrive_user | default(omit) }}"
    group: "{{ configdrive_group  | default(omit) }}"
    mode: 0755
    recurse: yes
    state: directory
  with_items:
    - "openstack/2012-08-10"
    - "openstack/latest"
    - "openstack/content"

- include: configdrive.yml
  tags: ["configdrive", "core"]

- name: Cleanup instance configdrive folder
  file: 
    state: absent
    force: yes 
    name: "{{ configdrive_config_dir }}/{{ configdrive_instance_dir }}"
  when: >
    configdrive_config_dir_delete is defined 
    and configdrive_config_dir_delete

