---
rabbitmq_repo_release: "liberty"
rabbitmq_packages_install_recommends: true
rabbitmq_os_repo_url:
rabbitmq_os_repo_key:

rabbitmq_daemon: rabbitmq-server
rabbitmq_user: rabbitmq
rabbitmq_group: rabbitmq

rabbitmq_pidfile: /var/run/rabbitmq/pid
rabbitmq_ssl_dir: /etc/rabbitmq/ssl
rabbitmq_config: /etc/rabbitmq/rabbitmq.config
rabbitmq_confenv: /etc/rabbitmq/rabbitmq-env.conf
rabbitmq_plugin_dir: /usr/lib/rabbitmq/lib/

